using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MathLearning.Admin.Migrations
{
    /// <inheritdoc />
    public partial class AdminAuthoringSchemaSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            RenameTableIfNeeded(migrationBuilder, "Topic", "Topics");
            RenameTableIfNeeded(migrationBuilder, "Subtopic", "Subtopics");
            RenameTableIfNeeded(migrationBuilder, "QuestionTranslation", "QuestionTranslations");
            RenameTableIfNeeded(migrationBuilder, "QuestionStep", "QuestionSteps");
            RenameTableIfNeeded(migrationBuilder, "QuestionStepTranslation", "QuestionStepTranslations");
            RenameTableIfNeeded(migrationBuilder, "OptionTranslation", "OptionTranslations");

            RenameIndexIfNeeded(migrationBuilder, "IX_Subtopic_TopicId", "IX_Subtopics_TopicId");
            RenameIndexIfNeeded(migrationBuilder, "IX_QuestionTranslation_QuestionId", "IX_QuestionTranslations_QuestionId");
            RenameIndexIfNeeded(migrationBuilder, "IX_QuestionStep_QuestionId", "IX_QuestionSteps_QuestionId");
            RenameIndexIfNeeded(migrationBuilder, "IX_QuestionStepTranslation_QuestionStepId", "IX_QuestionStepTranslations_QuestionStepId");
            RenameIndexIfNeeded(migrationBuilder, "IX_OptionTranslation_OptionId", "IX_OptionTranslations_OptionId");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "Topics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NULL,
    CONSTRAINT "PK_Topics" PRIMARY KEY ("Id")
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "Subtopics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "TopicId" integer NOT NULL,
    CONSTRAINT "PK_Subtopics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subtopics_Topics_TopicId" FOREIGN KEY ("TopicId") REFERENCES "Topics" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "QuestionTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "Lang" text NOT NULL,
    "Text" text NOT NULL,
    "Explanation" text NULL,
    "HintFormula" text NULL,
    "HintClue" text NULL,
    "HintLight" text NULL,
    "HintMedium" text NULL,
    "HintFull" text NULL,
    CONSTRAINT "PK_QuestionTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuestionTranslations_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "QuestionSteps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "StepIndex" integer NOT NULL,
    "Text" text NOT NULL,
    "TextFormat" character varying(32) NOT NULL DEFAULT 'MarkdownWithMath',
    "HintFormat" character varying(32) NOT NULL DEFAULT 'MarkdownWithMath',
    "TextRenderMode" character varying(32) NOT NULL DEFAULT 'Auto',
    "HintRenderMode" character varying(32) NOT NULL DEFAULT 'Auto',
    "SemanticsAltText" character varying(500) NULL,
    "Hint" TEXT NULL,
    "Highlight" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_QuestionSteps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuestionSteps_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "QuestionStepTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionStepId" integer NOT NULL,
    "Lang" text NOT NULL,
    "Text" text NOT NULL,
    "Hint" text NULL,
    CONSTRAINT "PK_QuestionStepTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuestionStepTranslations_QuestionSteps_QuestionStepId" FOREIGN KEY ("QuestionStepId") REFERENCES "QuestionSteps" ("Id") ON DELETE CASCADE
);
""");

            migrationBuilder.Sql("""
CREATE TABLE IF NOT EXISTS "OptionTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OptionId" integer NOT NULL,
    "Lang" text NOT NULL,
    "Text" text NOT NULL,
    CONSTRAINT "PK_OptionTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OptionTranslations_Options_OptionId" FOREIGN KEY ("OptionId") REFERENCES "Options" ("Id") ON DELETE CASCADE
);
""");

            AddColumnIfMissing(migrationBuilder, "Questions", "Type", "text NOT NULL DEFAULT 'multiple_choice'");
            AddColumnIfMissing(migrationBuilder, "Questions", "CorrectAnswer", "text NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "SubtopicId", "integer NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintFormula", "text NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintClue", "text NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintDifficulty", "integer NOT NULL DEFAULT 1");
            AddColumnIfMissing(migrationBuilder, "Questions", "CurrentDraftId", "uuid NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "CurrentVersionNumber", "integer NOT NULL DEFAULT 0");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintFull", "TEXT NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "PublishState", "text NOT NULL DEFAULT 'draft'");
            AddColumnIfMissing(migrationBuilder, "Questions", "PublishedAtUtc", "timestamp with time zone NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "PublishedByUserId", "text NULL");
            AddColumnIfMissing(migrationBuilder, "Questions", "TextFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "Questions", "ExplanationFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "Questions", "TextRenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "Questions", "ExplanationRenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "Questions", "HintRenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "Questions", "SemanticsAltText", "character varying(1000) NULL");

            AddColumnIfMissing(migrationBuilder, "Options", "TextFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "Options", "RenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "Options", "SemanticsAltText", "character varying(500) NULL");
            AddColumnIfMissing(migrationBuilder, "Options", "Order", "integer NOT NULL DEFAULT 0");

            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "TextFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "HintFormat", "character varying(32) NOT NULL DEFAULT 'MarkdownWithMath'");
            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "TextRenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "HintRenderMode", "character varying(32) NOT NULL DEFAULT 'Auto'");
            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "SemanticsAltText", "character varying(500) NULL");
            AddColumnIfMissing(migrationBuilder, "QuestionSteps", "Highlight", "boolean NOT NULL DEFAULT FALSE");

            AddColumnIfMissing(migrationBuilder, "QuestionTranslations", "HintLight", "text NULL");
            AddColumnIfMissing(migrationBuilder, "QuestionTranslations", "HintMedium", "text NULL");
            AddColumnIfMissing(migrationBuilder, "QuestionTranslations", "HintFull", "text NULL");

            SetDefaultIfTableExists(migrationBuilder, "Questions", "Type", "'multiple_choice'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "HintDifficulty", "1");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "CurrentVersionNumber", "0");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "PublishState", "'draft'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "TextFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "ExplanationFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "HintFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "TextRenderMode", "'Auto'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "ExplanationRenderMode", "'Auto'");
            SetDefaultIfTableExists(migrationBuilder, "Questions", "HintRenderMode", "'Auto'");

            SetDefaultIfTableExists(migrationBuilder, "Options", "TextFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "Options", "RenderMode", "'Auto'");
            SetDefaultIfTableExists(migrationBuilder, "Options", "Order", "0");

            SetDefaultIfTableExists(migrationBuilder, "QuestionSteps", "TextFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "QuestionSteps", "HintFormat", "'MarkdownWithMath'");
            SetDefaultIfTableExists(migrationBuilder, "QuestionSteps", "TextRenderMode", "'Auto'");
            SetDefaultIfTableExists(migrationBuilder, "QuestionSteps", "HintRenderMode", "'Auto'");
            SetDefaultIfTableExists(migrationBuilder, "QuestionSteps", "Highlight", "FALSE");

            migrationBuilder.Sql("""
INSERT INTO "Topics" ("Name", "Description")
SELECT 'Osnove Algebre', 'Jednačine, nejednačine i izrazi'
WHERE NOT EXISTS (
    SELECT 1
    FROM "Topics"
    WHERE "Name" = 'Osnove Algebre'
);

INSERT INTO "Topics" ("Name", "Description")
SELECT 'Osnove Geometrije', 'Osnovni geometrijski pojmovi'
WHERE NOT EXISTS (
    SELECT 1
    FROM "Topics"
    WHERE "Name" = 'Osnove Geometrije'
);

INSERT INTO "Topics" ("Name", "Description")
SELECT 'Sabiranje i Oduzimanje', 'Osnovne aritmetičke operacije'
WHERE NOT EXISTS (
    SELECT 1
    FROM "Topics"
    WHERE "Name" = 'Sabiranje i Oduzimanje'
);

INSERT INTO "Subtopics" ("Name", "TopicId")
SELECT 'Jednačine', t."Id"
FROM "Topics" t
WHERE t."Name" = 'Osnove Algebre'
  AND NOT EXISTS (
      SELECT 1
      FROM "Subtopics" s
      WHERE s."Name" = 'Jednačine' AND s."TopicId" = t."Id"
  );

INSERT INTO "Subtopics" ("Name", "TopicId")
SELECT 'Nejednačine', t."Id"
FROM "Topics" t
WHERE t."Name" = 'Osnove Algebre'
  AND NOT EXISTS (
      SELECT 1
      FROM "Subtopics" s
      WHERE s."Name" = 'Nejednačine' AND s."TopicId" = t."Id"
  );

INSERT INTO "Subtopics" ("Name", "TopicId")
SELECT 'Trouglovi', t."Id"
FROM "Topics" t
WHERE t."Name" = 'Osnove Geometrije'
  AND NOT EXISTS (
      SELECT 1
      FROM "Subtopics" s
      WHERE s."Name" = 'Trouglovi' AND s."TopicId" = t."Id"
  );

INSERT INTO "Subtopics" ("Name", "TopicId")
SELECT 'Sabiranje do 100', t."Id"
FROM "Topics" t
WHERE t."Name" = 'Sabiranje i Oduzimanje'
  AND NOT EXISTS (
      SELECT 1
      FROM "Subtopics" s
      WHERE s."Name" = 'Sabiranje do 100' AND s."TopicId" = t."Id"
  );

INSERT INTO "Subtopics" ("Name", "TopicId")
SELECT 'Množenje i Deljenje', t."Id"
FROM "Topics" t
WHERE t."Name" = 'Sabiranje i Oduzimanje'
  AND NOT EXISTS (
      SELECT 1
      FROM "Subtopics" s
      WHERE s."Name" = 'Množenje i Deljenje' AND s."TopicId" = t."Id"
  );
""");

            migrationBuilder.Sql("""
UPDATE "Questions" q
SET "SubtopicId" = s."Id"
FROM "Categories" c
JOIN "Subtopics" s ON s."Name" = 'Jednačine'
WHERE q."CategoryId" = c."Id"
  AND c."Name" = 'Algebra'
  AND (q."SubtopicId" IS NULL OR q."SubtopicId" = 0);

UPDATE "Questions" q
SET "SubtopicId" = s."Id"
FROM "Categories" c
JOIN "Subtopics" s ON s."Name" = 'Trouglovi'
WHERE q."CategoryId" = c."Id"
  AND c."Name" = 'Geometrija'
  AND (q."SubtopicId" IS NULL OR q."SubtopicId" = 0);

UPDATE "Questions" q
SET "SubtopicId" = s."Id"
FROM "Categories" c
JOIN "Subtopics" s ON s."Name" = 'Sabiranje do 100'
WHERE q."CategoryId" = c."Id"
  AND c."Name" = 'Aritmetika'
  AND (q."SubtopicId" IS NULL OR q."SubtopicId" = 0);

UPDATE "Questions" q
SET "SubtopicId" = fallback."Id"
FROM (
    SELECT "Id"
    FROM "Subtopics"
    ORDER BY "Id"
    LIMIT 1
) fallback
WHERE q."SubtopicId" IS NULL
   OR q."SubtopicId" = 0
   OR NOT EXISTS (
       SELECT 1
       FROM "Subtopics" s
       WHERE s."Id" = q."SubtopicId"
   );
""");

            migrationBuilder.Sql("""
DO $$
BEGIN
    IF to_regclass('public."Questions"') IS NOT NULL THEN
        ALTER TABLE "Questions" ALTER COLUMN "SubtopicId" SET NOT NULL;
    END IF;
END
$$;
""");

            CreateIndexIfMissing(migrationBuilder, "IX_Subtopics_TopicId", @"CREATE INDEX IF NOT EXISTS ""IX_Subtopics_TopicId"" ON ""Subtopics"" (""TopicId"")");
            CreateIndexIfMissing(migrationBuilder, "IX_Questions_SubtopicId", @"CREATE INDEX IF NOT EXISTS ""IX_Questions_SubtopicId"" ON ""Questions"" (""SubtopicId"")");
            CreateIndexIfMissing(migrationBuilder, "IX_QuestionTranslations_QuestionId", @"CREATE INDEX IF NOT EXISTS ""IX_QuestionTranslations_QuestionId"" ON ""QuestionTranslations"" (""QuestionId"")");
            CreateIndexIfMissing(migrationBuilder, "IX_QuestionSteps_QuestionId", @"CREATE INDEX IF NOT EXISTS ""IX_QuestionSteps_QuestionId"" ON ""QuestionSteps"" (""QuestionId"")");
            CreateIndexIfMissing(migrationBuilder, "IX_QuestionStepTranslations_QuestionStepId", @"CREATE INDEX IF NOT EXISTS ""IX_QuestionStepTranslations_QuestionStepId"" ON ""QuestionStepTranslations"" (""QuestionStepId"")");
            CreateIndexIfMissing(migrationBuilder, "IX_OptionTranslations_OptionId", @"CREATE INDEX IF NOT EXISTS ""IX_OptionTranslations_OptionId"" ON ""OptionTranslations"" (""OptionId"")");

            RecreateCategoryForeignKeyWithRestrict(migrationBuilder);
            AddForeignKeyIfMissing(migrationBuilder, "FK_Questions_Subtopics_SubtopicId", "Questions", "SubtopicId", "Subtopics", "Id", "CASCADE");
            AddForeignKeyIfMissing(migrationBuilder, "FK_Subtopics_Topics_TopicId", "Subtopics", "TopicId", "Topics", "Id", "CASCADE");
            AddForeignKeyIfMissing(migrationBuilder, "FK_QuestionTranslations_Questions_QuestionId", "QuestionTranslations", "QuestionId", "Questions", "Id", "CASCADE");
            AddForeignKeyIfMissing(migrationBuilder, "FK_QuestionSteps_Questions_QuestionId", "QuestionSteps", "QuestionId", "Questions", "Id", "CASCADE");
            AddForeignKeyIfMissing(migrationBuilder, "FK_QuestionStepTranslations_QuestionSteps_QuestionStepId", "QuestionStepTranslations", "QuestionStepId", "QuestionSteps", "Id", "CASCADE");
            AddForeignKeyIfMissing(migrationBuilder, "FK_OptionTranslations_Options_OptionId", "OptionTranslations", "OptionId", "Options", "Id", "CASCADE");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // This migration repairs multiple historical admin schema states and is intentionally non-destructive on downgrade.
        }

        private static void RenameTableIfNeeded(MigrationBuilder migrationBuilder, string oldName, string newName)
        {
            migrationBuilder.Sql($@"
DO $$
BEGIN
    IF to_regclass('public.""{newName}""') IS NULL AND to_regclass('public.""{oldName}""') IS NOT NULL THEN
        EXECUTE 'ALTER TABLE ""{oldName}"" RENAME TO ""{newName}""';
    END IF;
END
$$;
");
        }

        private static void RenameIndexIfNeeded(MigrationBuilder migrationBuilder, string oldName, string newName)
        {
            migrationBuilder.Sql($@"
DO $$
BEGIN
    IF to_regclass('public.""{newName}""') IS NULL AND to_regclass('public.""{oldName}""') IS NOT NULL THEN
        EXECUTE 'ALTER INDEX ""{oldName}"" RENAME TO ""{newName}""';
    END IF;
END
$$;
");
        }

        private static void AddColumnIfMissing(MigrationBuilder migrationBuilder, string table, string column, string definition)
        {
            migrationBuilder.Sql($@"ALTER TABLE IF EXISTS ""{table}"" ADD COLUMN IF NOT EXISTS ""{column}"" {definition};");
        }

        private static void SetDefaultIfTableExists(MigrationBuilder migrationBuilder, string table, string column, string defaultValueSql)
        {
            migrationBuilder.Sql($@"ALTER TABLE IF EXISTS ""{table}"" ALTER COLUMN ""{column}"" SET DEFAULT {defaultValueSql};");
        }

        private static void CreateIndexIfMissing(MigrationBuilder migrationBuilder, string indexName, string createSql)
        {
            migrationBuilder.Sql(createSql);
        }

        private static void RecreateCategoryForeignKeyWithRestrict(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
DO $$
BEGIN
    IF to_regclass('public."Questions"') IS NULL OR to_regclass('public."Categories"') IS NULL THEN
        RETURN;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_Questions_Categories_CategoryId'
    ) THEN
        ALTER TABLE "Questions" DROP CONSTRAINT "FK_Questions_Categories_CategoryId";
    END IF;

    ALTER TABLE "Questions"
        ADD CONSTRAINT "FK_Questions_Categories_CategoryId"
        FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT;
END
$$;
""");
        }

        private static void AddForeignKeyIfMissing(
            MigrationBuilder migrationBuilder,
            string constraintName,
            string table,
            string column,
            string principalTable,
            string principalColumn,
            string onDeleteAction)
        {
            migrationBuilder.Sql($@"
DO $$
BEGIN
    IF to_regclass('public.""{table}""') IS NULL OR to_regclass('public.""{principalTable}""') IS NULL THEN
        RETURN;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = '{constraintName}'
    ) THEN
        EXECUTE 'ALTER TABLE ""{table}"" ADD CONSTRAINT ""{constraintName}"" FOREIGN KEY (""{column}"") REFERENCES ""{principalTable}"" (""{principalColumn}"") ON DELETE {onDeleteAction}';
    END IF;
END
$$;
");
        }
    }
}
